//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TermProject.CloudWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CloudWSSoap", Namespace="http://tempuri.org/")]
    public partial class CloudWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback addDownloadDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPreviousDownloadDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPreviousFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletePreviousVersionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateDownloadDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMaxFileIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPreviousDownloadDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDownloadDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteAllFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback resetStorageUsedOperationCompleted;
        
        private System.Threading.SendOrPostCallback logUserTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CloudWS() {
            this.Url = global::TermProject.Properties.Settings.Default.TermProject_CloudWS_CloudWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event addDownloadDataCompletedEventHandler addDownloadDataCompleted;
        
        /// <remarks/>
        public event addPreviousDownloadDataCompletedEventHandler addPreviousDownloadDataCompleted;
        
        /// <remarks/>
        public event getPreviousFilesCompletedEventHandler getPreviousFilesCompleted;
        
        /// <remarks/>
        public event deletePreviousVersionsCompletedEventHandler deletePreviousVersionsCompleted;
        
        /// <remarks/>
        public event updateDownloadDataCompletedEventHandler updateDownloadDataCompleted;
        
        /// <remarks/>
        public event getMaxFileIDCompletedEventHandler getMaxFileIDCompleted;
        
        /// <remarks/>
        public event getPreviousDownloadDataCompletedEventHandler getPreviousDownloadDataCompleted;
        
        /// <remarks/>
        public event getDownloadDataCompletedEventHandler getDownloadDataCompleted;
        
        /// <remarks/>
        public event DeleteFileCompletedEventHandler DeleteFileCompleted;
        
        /// <remarks/>
        public event deleteAccountCompletedEventHandler deleteAccountCompleted;
        
        /// <remarks/>
        public event deleteAllFilesCompletedEventHandler deleteAllFilesCompleted;
        
        /// <remarks/>
        public event resetStorageUsedCompletedEventHandler resetStorageUsedCompleted;
        
        /// <remarks/>
        public event logUserTransactionCompletedEventHandler logUserTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addDownloadData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addDownloadData(int accountID, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data, int verification) {
            object[] results = this.Invoke("addDownloadData", new object[] {
                        accountID,
                        data,
                        verification});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addDownloadDataAsync(int accountID, byte[] data, int verification) {
            this.addDownloadDataAsync(accountID, data, verification, null);
        }
        
        /// <remarks/>
        public void addDownloadDataAsync(int accountID, byte[] data, int verification, object userState) {
            if ((this.addDownloadDataOperationCompleted == null)) {
                this.addDownloadDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddDownloadDataOperationCompleted);
            }
            this.InvokeAsync("addDownloadData", new object[] {
                        accountID,
                        data,
                        verification}, this.addDownloadDataOperationCompleted, userState);
        }
        
        private void OnaddDownloadDataOperationCompleted(object arg) {
            if ((this.addDownloadDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addDownloadDataCompleted(this, new addDownloadDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addPreviousDownloadData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPreviousDownloadData(int accountID, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data, int fileID, System.DateTime timestamp, string title, int length, int verification) {
            this.Invoke("addPreviousDownloadData", new object[] {
                        accountID,
                        data,
                        fileID,
                        timestamp,
                        title,
                        length,
                        verification});
        }
        
        /// <remarks/>
        public void addPreviousDownloadDataAsync(int accountID, byte[] data, int fileID, System.DateTime timestamp, string title, int length, int verification) {
            this.addPreviousDownloadDataAsync(accountID, data, fileID, timestamp, title, length, verification, null);
        }
        
        /// <remarks/>
        public void addPreviousDownloadDataAsync(int accountID, byte[] data, int fileID, System.DateTime timestamp, string title, int length, int verification, object userState) {
            if ((this.addPreviousDownloadDataOperationCompleted == null)) {
                this.addPreviousDownloadDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPreviousDownloadDataOperationCompleted);
            }
            this.InvokeAsync("addPreviousDownloadData", new object[] {
                        accountID,
                        data,
                        fileID,
                        timestamp,
                        title,
                        length,
                        verification}, this.addPreviousDownloadDataOperationCompleted, userState);
        }
        
        private void OnaddPreviousDownloadDataOperationCompleted(object arg) {
            if ((this.addPreviousDownloadDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPreviousDownloadDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPreviousFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getPreviousFiles(int accountID, int verification) {
            object[] results = this.Invoke("getPreviousFiles", new object[] {
                        accountID,
                        verification});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getPreviousFilesAsync(int accountID, int verification) {
            this.getPreviousFilesAsync(accountID, verification, null);
        }
        
        /// <remarks/>
        public void getPreviousFilesAsync(int accountID, int verification, object userState) {
            if ((this.getPreviousFilesOperationCompleted == null)) {
                this.getPreviousFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPreviousFilesOperationCompleted);
            }
            this.InvokeAsync("getPreviousFiles", new object[] {
                        accountID,
                        verification}, this.getPreviousFilesOperationCompleted, userState);
        }
        
        private void OngetPreviousFilesOperationCompleted(object arg) {
            if ((this.getPreviousFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPreviousFilesCompleted(this, new getPreviousFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deletePreviousVersions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deletePreviousVersions(int accountID, int verification) {
            this.Invoke("deletePreviousVersions", new object[] {
                        accountID,
                        verification});
        }
        
        /// <remarks/>
        public void deletePreviousVersionsAsync(int accountID, int verification) {
            this.deletePreviousVersionsAsync(accountID, verification, null);
        }
        
        /// <remarks/>
        public void deletePreviousVersionsAsync(int accountID, int verification, object userState) {
            if ((this.deletePreviousVersionsOperationCompleted == null)) {
                this.deletePreviousVersionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletePreviousVersionsOperationCompleted);
            }
            this.InvokeAsync("deletePreviousVersions", new object[] {
                        accountID,
                        verification}, this.deletePreviousVersionsOperationCompleted, userState);
        }
        
        private void OndeletePreviousVersionsOperationCompleted(object arg) {
            if ((this.deletePreviousVersionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletePreviousVersionsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateDownloadData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateDownloadData([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] newData, int fileID, int verification) {
            this.Invoke("updateDownloadData", new object[] {
                        newData,
                        fileID,
                        verification});
        }
        
        /// <remarks/>
        public void updateDownloadDataAsync(byte[] newData, int fileID, int verification) {
            this.updateDownloadDataAsync(newData, fileID, verification, null);
        }
        
        /// <remarks/>
        public void updateDownloadDataAsync(byte[] newData, int fileID, int verification, object userState) {
            if ((this.updateDownloadDataOperationCompleted == null)) {
                this.updateDownloadDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateDownloadDataOperationCompleted);
            }
            this.InvokeAsync("updateDownloadData", new object[] {
                        newData,
                        fileID,
                        verification}, this.updateDownloadDataOperationCompleted, userState);
        }
        
        private void OnupdateDownloadDataOperationCompleted(object arg) {
            if ((this.updateDownloadDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateDownloadDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMaxFileID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getMaxFileID(int verification) {
            object[] results = this.Invoke("getMaxFileID", new object[] {
                        verification});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getMaxFileIDAsync(int verification) {
            this.getMaxFileIDAsync(verification, null);
        }
        
        /// <remarks/>
        public void getMaxFileIDAsync(int verification, object userState) {
            if ((this.getMaxFileIDOperationCompleted == null)) {
                this.getMaxFileIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMaxFileIDOperationCompleted);
            }
            this.InvokeAsync("getMaxFileID", new object[] {
                        verification}, this.getMaxFileIDOperationCompleted, userState);
        }
        
        private void OngetMaxFileIDOperationCompleted(object arg) {
            if ((this.getMaxFileIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMaxFileIDCompleted(this, new getMaxFileIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPreviousDownloadData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getPreviousDownloadData(int fileID, long fileLength, string timestamp, int verification) {
            object[] results = this.Invoke("getPreviousDownloadData", new object[] {
                        fileID,
                        fileLength,
                        timestamp,
                        verification});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getPreviousDownloadDataAsync(int fileID, long fileLength, string timestamp, int verification) {
            this.getPreviousDownloadDataAsync(fileID, fileLength, timestamp, verification, null);
        }
        
        /// <remarks/>
        public void getPreviousDownloadDataAsync(int fileID, long fileLength, string timestamp, int verification, object userState) {
            if ((this.getPreviousDownloadDataOperationCompleted == null)) {
                this.getPreviousDownloadDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPreviousDownloadDataOperationCompleted);
            }
            this.InvokeAsync("getPreviousDownloadData", new object[] {
                        fileID,
                        fileLength,
                        timestamp,
                        verification}, this.getPreviousDownloadDataOperationCompleted, userState);
        }
        
        private void OngetPreviousDownloadDataOperationCompleted(object arg) {
            if ((this.getPreviousDownloadDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPreviousDownloadDataCompleted(this, new getPreviousDownloadDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDownloadData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getDownloadData(int fileID, long fileLength, int verification) {
            object[] results = this.Invoke("getDownloadData", new object[] {
                        fileID,
                        fileLength,
                        verification});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getDownloadDataAsync(int fileID, long fileLength, int verification) {
            this.getDownloadDataAsync(fileID, fileLength, verification, null);
        }
        
        /// <remarks/>
        public void getDownloadDataAsync(int fileID, long fileLength, int verification, object userState) {
            if ((this.getDownloadDataOperationCompleted == null)) {
                this.getDownloadDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDownloadDataOperationCompleted);
            }
            this.InvokeAsync("getDownloadData", new object[] {
                        fileID,
                        fileLength,
                        verification}, this.getDownloadDataOperationCompleted, userState);
        }
        
        private void OngetDownloadDataOperationCompleted(object arg) {
            if ((this.getDownloadDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDownloadDataCompleted(this, new getDownloadDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteFile(int fileID, int verification) {
            object[] results = this.Invoke("DeleteFile", new object[] {
                        fileID,
                        verification});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFileAsync(int fileID, int verification) {
            this.DeleteFileAsync(fileID, verification, null);
        }
        
        /// <remarks/>
        public void DeleteFileAsync(int fileID, int verification, object userState) {
            if ((this.DeleteFileOperationCompleted == null)) {
                this.DeleteFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFileOperationCompleted);
            }
            this.InvokeAsync("DeleteFile", new object[] {
                        fileID,
                        verification}, this.DeleteFileOperationCompleted, userState);
        }
        
        private void OnDeleteFileOperationCompleted(object arg) {
            if ((this.DeleteFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFileCompleted(this, new DeleteFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteAccount(int ID, int adminID, int verification) {
            object[] results = this.Invoke("deleteAccount", new object[] {
                        ID,
                        adminID,
                        verification});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAccountAsync(int ID, int adminID, int verification) {
            this.deleteAccountAsync(ID, adminID, verification, null);
        }
        
        /// <remarks/>
        public void deleteAccountAsync(int ID, int adminID, int verification, object userState) {
            if ((this.deleteAccountOperationCompleted == null)) {
                this.deleteAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteAccountOperationCompleted);
            }
            this.InvokeAsync("deleteAccount", new object[] {
                        ID,
                        adminID,
                        verification}, this.deleteAccountOperationCompleted, userState);
        }
        
        private void OndeleteAccountOperationCompleted(object arg) {
            if ((this.deleteAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteAccountCompleted(this, new deleteAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteAllFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteAllFiles(int ID, int verification) {
            object[] results = this.Invoke("deleteAllFiles", new object[] {
                        ID,
                        verification});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAllFilesAsync(int ID, int verification) {
            this.deleteAllFilesAsync(ID, verification, null);
        }
        
        /// <remarks/>
        public void deleteAllFilesAsync(int ID, int verification, object userState) {
            if ((this.deleteAllFilesOperationCompleted == null)) {
                this.deleteAllFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteAllFilesOperationCompleted);
            }
            this.InvokeAsync("deleteAllFiles", new object[] {
                        ID,
                        verification}, this.deleteAllFilesOperationCompleted, userState);
        }
        
        private void OndeleteAllFilesOperationCompleted(object arg) {
            if ((this.deleteAllFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteAllFilesCompleted(this, new deleteAllFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/resetStorageUsed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int resetStorageUsed(int ID, int verification) {
            object[] results = this.Invoke("resetStorageUsed", new object[] {
                        ID,
                        verification});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void resetStorageUsedAsync(int ID, int verification) {
            this.resetStorageUsedAsync(ID, verification, null);
        }
        
        /// <remarks/>
        public void resetStorageUsedAsync(int ID, int verification, object userState) {
            if ((this.resetStorageUsedOperationCompleted == null)) {
                this.resetStorageUsedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetStorageUsedOperationCompleted);
            }
            this.InvokeAsync("resetStorageUsed", new object[] {
                        ID,
                        verification}, this.resetStorageUsedOperationCompleted, userState);
        }
        
        private void OnresetStorageUsedOperationCompleted(object arg) {
            if ((this.resetStorageUsedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resetStorageUsedCompleted(this, new resetStorageUsedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/logUserTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void logUserTransaction(int accountID, string description, int verification) {
            this.Invoke("logUserTransaction", new object[] {
                        accountID,
                        description,
                        verification});
        }
        
        /// <remarks/>
        public void logUserTransactionAsync(int accountID, string description, int verification) {
            this.logUserTransactionAsync(accountID, description, verification, null);
        }
        
        /// <remarks/>
        public void logUserTransactionAsync(int accountID, string description, int verification, object userState) {
            if ((this.logUserTransactionOperationCompleted == null)) {
                this.logUserTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogUserTransactionOperationCompleted);
            }
            this.InvokeAsync("logUserTransaction", new object[] {
                        accountID,
                        description,
                        verification}, this.logUserTransactionOperationCompleted, userState);
        }
        
        private void OnlogUserTransactionOperationCompleted(object arg) {
            if ((this.logUserTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logUserTransactionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void addDownloadDataCompletedEventHandler(object sender, addDownloadDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addDownloadDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addDownloadDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void addPreviousDownloadDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getPreviousFilesCompletedEventHandler(object sender, getPreviousFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPreviousFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPreviousFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deletePreviousVersionsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void updateDownloadDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getMaxFileIDCompletedEventHandler(object sender, getMaxFileIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMaxFileIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMaxFileIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getPreviousDownloadDataCompletedEventHandler(object sender, getPreviousDownloadDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPreviousDownloadDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPreviousDownloadDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDownloadDataCompletedEventHandler(object sender, getDownloadDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDownloadDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDownloadDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteFileCompletedEventHandler(object sender, DeleteFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteAccountCompletedEventHandler(object sender, deleteAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteAllFilesCompletedEventHandler(object sender, deleteAllFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteAllFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteAllFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void resetStorageUsedCompletedEventHandler(object sender, resetStorageUsedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resetStorageUsedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal resetStorageUsedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void logUserTransactionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591